### ISSUE TITLE
How to access zpanel when your domain has expired?

### ISSUE THREAD

**Issue by evivz** [zpanel/zpanel#2]
Hi,

My domain has expired. I had setup zpanel to be accessed from zpanel.domain.com

Now how Can I access it from IP address? Any way to change the subdomain from ssh?

Thanks

**Comment by evivz** [comment]
@Alf71  How to do that?

**Comment by evivz** [comment]
Thanks it worked.

**Comment by Alf71** [comment]
http://docs.zpanelcp.com/?node=48
