### ISSUE TITLE
PHP mysql_* functions.

### ISSUE THREAD

**Issue by iberflow** [zpanel/zpanel#3]
Hi folks,
I think that PHP 5.3 is quite an old version, therefore most of mine and I'd assume others' deployments are using v5.5 in which mysql_\* functions are deprecated and unsafe(!) so it should be replaced with PDO.

From what I've seen (I haven't seen all of the code) most code uses mysql_\* functions.
I think this is a massive issue, which should be taken into consideration for the next update. I will try to find some time myself to contribute and rewrite it, but obviously it's a community driven project so if anyone has started doing it, I'd like to give a hand.

P.S. Main attraction of Zpanel for me, was the aesthetic design (better than most paid products). Most of other platforms look like crap, so well done guys. Love the UI and the functionality. I'll try to contribute as much as I can.

**Comment by Caffe1neAdd1ct** [comment]
Hi Bernotas,

Most of the application should now be running through PDO, have you
definitely installed the latest 10.1.1 version?

Could you post up all notices from your error log showing where the mysql_
functions are?

Kind regards,
Kev

On 31 Jul 2014, at 00:22, Ignas Bernotas notifications@github.com wrote:

Hi folks,
I think that PHP 5.3 is quite an old version, therefore most of mine and
I'd assume others' deployments are using v5.5 in which mysql_\* functions
are deprecated and unsafe(!) so it should be replaced with PDO.

From what I've seen (I haven't seen all of the code) most code uses mysql_*
functions.
I think this is a massive issue, which should be taken into consideration
for the next update. I will try to find some time myself to contribute and
rewrite it, but obviously it's a community driven project so if anyone has
started doing it, I'd like to give a hand.

P.S. Main attraction of Zpanel for me, was the aesthetic design (better
than most paid products). Most of other platforms look like crap, so well
done guys. Love the UI and the functionality. I'll try to contribute as
much as I can.

—
Reply to this email directly or view it on GitHub
https://github.com/zpanel/zpanel/issues/3.

**Comment by iberflow** [comment]
God I feel silly, I did install 10.1.1 but I've looked at this repo's code and not zpanelx.. Closing the issue now :)
