### ISSUE TITLE
get logins

### ISSUE THREAD

**Issue by hellofantastic** [zpanel/zpanel#5]
Hey there,

So I installed zpanel from command line... and terminal hung at this part 
Total download size: 93 M
Installed size: 251 M
Downloading Packages:
then did this
Read from remote host [ip address]: Operation timed out
Connection to [ip address] closed.

So i went to the subdomain in browser just to check and voila the login panel except I dodn't see the script completion with the logins and passwords so how do I get them? I tried forgot password on the login screen but nothing happened.

**Comment by hcaz** [comment]
nano /root/passwords.txt
That should tell you

Though you might need to scrap the install and start again if it did hang

**Comment by hellofantastic** [comment]
hey fast.. thanks so much, they are there... now any reason the forgot password didn't work is it becasue I havent logged in and set anything?

**Comment by hcaz** [comment]
I got an email about this and wasn't busy:P
I didn't know there was a forgot password so i can not help you there (Been a while since I used zPanel now), but if you login with them details you should be able to change the password.

**Comment by Caffe1neAdd1ct** [comment]
Forgotten password would only work once you have set the zadmin details up, from memory it would need a valid email to send you a reset url.

**Comment by hellofantastic** [comment]
a side note .. is zpanel still active? all the community forum links just load the zpenal homepage

**Comment by Caffe1neAdd1ct** [comment]
Have a look at sentora.org

**Comment by hellofantastic** [comment]
ah ok I see what you did there.... so zpanel is still supported , I just toiled on setuping a vps and domains and nameservers and getting zpanel and zantastic0x going and its working right now... is there a migration/update method if I get to the point of wanting to go sentora?

**Comment by hellofantastic** [comment]
I tried joining the forum but it decided I was a spammer? and wouldn't let me in

On 2014-10-21, at 4:27 PM, Kevin Andrews wrote:

Have a look at sentora.org

—
Reply to this email directly or view it on GitHub.

Dallas Larsen
Principal at hellofantastic
dallas@hellofantastic.com
250.509.0036
www.hellofantastic.com

**Comment by hellofantastic** [comment]
also if you guys see this... I added zantasticox to zpanel to add fantastico like install of wordpress sites only to find that it has all folders and files set to 777 upon install of wordpress sites, I chmod directories to  755 and files 644 but then my ftp user can't write...and read on lowendtalk that zpanel is not secure enough for production use....... soo would I be in better shape if I blew away my vps started over with sentora stable off of github? does it have zantastico/fantastico module?
