### ISSUE TITLE
Blank page when creating new client

### ISSUE THREAD

**Issue by IliaIdakiev** [zpanel/zpanel#7]
Using zPanel for CentOS 6.4 after I create a new user I get redirected to: <ip_addr>/?module=manage_clients&action=CreateClient and the page is blank. I checked the error log /var/logs/httpd/error_log and didn't find anything serious:

File does not exist: ..../jquery.min.map refer to <ip_addr>
File does not exist: .../favicon.ico refer to <ip_addr>/?module=manage_clients&action=CreateClient

Edit:
Same thing happenes when I click Webalizer stats.

**Comment by hcaz** [comment]
Hello,
If i remember correctly zPanel is no longer under development, they took the code and re branded it under http://www.sentora.org/.
Might be worth going there if zPanel is having issues.

Sorry i cant help you

**Comment by IliaIdakiev** [comment]
Thank you very much!
