### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by BitFros7y** [zpanel/zpanel#9]
Hey guys, im running a small VPS (1gb ram) and hosting few websites.
I would like to install zPanel to make my life easier in managing websites, but im not sure if i have to delete my current lamp stack and other things or will zPanel installer take care all of that. Also if i must delete current softwares that what i have to delete except lamp (ftp ?) and do i have to delete all files (including configurations)?

**Comment by bluebrad** [comment]
do you know how to use SSH / Putty ? you will need root to install... 
also dont install Zpanel you will need to install Sentora.

**Comment by BitFros7y** [comment]
Yes i know how to use ssh and i have root access (actually i use sudo, and i can enable root, but im pretty sure i wont will need root)

And thx for suggesting me Sentora, now i see why half of the links at zPanel doesnt work. If i need any help with Sentora i will open ticket there.

**Comment by bluebrad** [comment]
http://docs.sentora.org/?node=22
